#!/usr/bin/env bash
# Write .env.docker from the running local Supabase stack.
#
# The CLI's local keys are fixed development credentials, identical on every
# machine and safe to regenerate at any time. .env.docker is gitignored.
set -euo pipefail
cd "$(dirname "$0")/.."

if ! supabase status >/dev/null 2>&1; then
  echo "Supabase is not running. Start it first:" >&2
  echo "  supabase start" >&2
  exit 1
fi

eval "$(supabase status -o env)"

cat > .env.docker <<VARS
# Generated by npm run docker:env — do not edit by hand.
# Local Supabase development keys; not secrets.
NEXT_PUBLIC_SUPABASE_URL=http://host.docker.internal:54321
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
NEXT_PUBLIC_SITE_URL=http://localhost:3000
VARS

echo "Wrote .env.docker"
echo "  API      http://127.0.0.1:54321"
echo "  Studio   http://127.0.0.1:54323"
echo "  Inbucket http://127.0.0.1:54324   (magic-link emails land here)"
